# Generated by Django 6.1 on 2026-08-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcn', models.CharField(blank=True, max_length=50, null=True)),
                ('sr', models.CharField(blank=True, max_length=50, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fase', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'proyectos',
                'managed': False,
            },
        ),
    ]
