# Generated by Django 6.1 on 2026-08-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio RCN')),
                ('sr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio SR')),
                ('proyecto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Proyecto')),
                ('responsable', models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsable')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('prioridad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prioridad')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('fase', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fase del Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
                'managed': True,
            },
        ),
    ]
