# Generated by Django 6.1 on 2026-08-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueRedmine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status_id', models.IntegerField()),
                ('priority_id', models.IntegerField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'issues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio / ID')),
                ('grupo_tarea', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo de tarea')),
                ('asignado_a', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asignado a')),
                ('asunto', models.TextField(verbose_name='Asunto / Descripción')),
                ('estado', models.CharField(default='Backlog', max_length=100, verbose_name='Estado')),
                ('prioridad_ept', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prioridad EPT')),
                ('fase', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fase')),
                ('impacto_otros', models.TextField(blank=True, null=True, verbose_name='Impacto de Otros Proyectos')),
                ('tipo_requerimiento', models.CharField(choices=[('ACTIVOS', 'Activos'), ('BACKLOG', 'Backlog'), ('CONCLUIDOS', 'Concluidos'), ('SR', 'Solicitud de Requerimiento (SR)'), ('RCN', 'RCN')], default='BACKLOG', max_length=20, verbose_name='Tipo / Pestaña')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'db_table': 'requerimientos',
            },
        ),
    ]
